name: pull_request
on: pull_request
jobs:
  lint-unit-test:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/set_up_flutter
      - name: Lint
        run: flutter analyze
      - name: Unit tests
        run: flutter test
  build-Android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/set_up_flutter
      - name: Build apk
        run: flutter build apk --release --split-per-abi
  build-iOS:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/set_up_flutter
      - name: Build ipa
        run: flutter build ios --release --no-codesign
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/set_up_flutter
      - name: Build web
        run: flutter build web --release
