name: pull_request
on: pull_request
jobs:
  lint-unit-test:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Install packages
        run:
          flutter pub get
      - name: Lint
        run: 
          flutter analyze
      - name: Unit tests
        run:
          flutter test
  build-Android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Build apk
        run:
          flutter build apk --release --split-per-abi
  build-iOS:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Build ipa
        run:
          flutter build ios --release --no-codesign
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Enable Web Support
        run:
          flutter config --enable-web
      - name: Build web
        run:
          flutter build web --release
